<a href="https://colab.research.google.com/github/Ivonne9140/ML_Ivonne/blob/main/Intro2NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy
numpy.__version__

'1.21.6'

In [14]:
import numpy as np

In [15]:
np?

In [16]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
type(L[0])

int

In [18]:
L2=[str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [19]:
type(L2[0])

str

In [20]:
L3=[True,"2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [21]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#integer array:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [25]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [26]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

https://numpy.org/doc/stable/user/absolute_beginners.html

https://numpy.org/doc/stable/user/quickstart.html#quickstart-array-creation


In [27]:
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [34]:
a=np.array([1,2,3,4,5,6])
a
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b
a

array([1, 2, 3, 4, 5, 6])

In [36]:
print(b[0])

[1 2 3 4]


In [37]:
a =np.array([1,2,3])

In [38]:
np.zeros(2)

array([0., 0.])

In [39]:
np.ones(2)

array([1., 1.])

In [40]:
np.empty(2)

array([1., 1.])

In [41]:
np.arange(4)

array([0, 1, 2, 3])

In [42]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [45]:
np.linspace(0,10,num=7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [49]:
x=np.ones(5,dtype=np.int64)
x


array([1, 1, 1, 1, 1])

In [52]:
import numpy as np
a=np.array([2,3,4])
a
a.dtype
b=np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [60]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [61]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [62]:
c=np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])